#ifndef COMMANDS_H
#define COMMANDS_H


#define SSD1306_ADDR 0x3C

// control byte - needed before setting a command
#define COMMAND_CONTROL_BYTE 0x00

// 0xAE: Display OFF
#define DISPLAY_OFF_COMMAND 0xAE

// 0xD5: Set Display Clock Divide Ratio - default is enough
#define DISPLAY_CLOCK_DIVIDE_RATIO_COMMAND 0xD5
#define DISPLAY_CLOCK_DIVIDE_RATIO_ARG_DEFAULT 0x80

// 0xA8: Set Multiplex Ratio - for 128x64 display
#define SET_MULTIPLEX_RATIO_COMMAND 0xA8
#define MULTIPLEX_RATIO_128X64 0x3F

// 0xD3: Set Display Offset - no offset
#define SET_DISPLAY_OFFSET_COMMAND 0xD3
#define DISPLAY_OFFSET_NONE 0x00

// 0x40: Set Display Start Line (0)
#define SET_START_LINE_COMMAND 0x40

// 0x8D: Charge Pump Setting - enable internal pump
#define CHARGE_PUMP_SETTING_COMMAND 0x8D
#define CHARGE_PUMP_ENABLE 0x14

// 0x20: Set Memory Addressing Mode - horizontal
#define MEMORY_ADDR_MODE_COMMAND 0x20
#define MEMORY_ADDR_MODE_HORIZONTAL 0x00

// 0xA1: Segment Remap - mirror horizontally
#define SEGMENT_REMAP_COMMAND 0xA1

// 0xC8: COM Output Scan Direction - mirror vertically (COM63→COM0)
#define COM_OUTPUT_SCAN_DIR_COMMAND 0xC8

// 0xDA: Set COM Pins Hardware Config - suitable for 128x64
#define COM_PINS_CONFIG_COMMAND 0xDA
#define COM_PINS_CONFIG_128X64 0x12

// 0x81: Set Contrast Control - brightness
#define SET_CONTRAST_COMMAND 0x81
#define DEFAULT_CONTRAST 0xCF

// 0xD9: Set Pre-charge Period - default value
#define SET_PRECHARGE_PERIOD_COMMAND 0xD9
#define DEFAULT_PRECHARGE_PERIOD 0xF1

// 0xDB: Set VCOMH Deselect Level - pixel OFF voltage level
#define SET_VCOMH_DESELECT_LEVEL_COMMAND 0xDB
#define DEFAULT_VCOMH_LEVEL 0x40

// 0xA4: Entire Display ON (resume RAM content)
#define ENTIRE_DISPLAY_ON_RESUME_COMMAND 0xA4

// 0xA6: Set Normal/Inverse Display - normal (non-inverted)
#define NORMAL_DISPLAY_COMMAND 0xA6

// 0xAF: Display ON
#define DISPLAY_ON_COMMAND 0xAF

static const uint8_t init_sequence[] = {
    COMMAND_CONTROL_BYTE, DISPLAY_OFF_COMMAND,
    COMMAND_CONTROL_BYTE, DISPLAY_CLOCK_DIVIDE_RATIO_COMMAND, DISPLAY_CLOCK_DIVIDE_RATIO_ARG_DEFAULT,
    COMMAND_CONTROL_BYTE, SET_MULTIPLEX_RATIO_COMMAND, MULTIPLEX_RATIO_128X64,
    COMMAND_CONTROL_BYTE, SET_DISPLAY_OFFSET_COMMAND, DISPLAY_OFFSET_NONE,
    COMMAND_CONTROL_BYTE, SET_START_LINE_COMMAND,
    COMMAND_CONTROL_BYTE, CHARGE_PUMP_SETTING_COMMAND, CHARGE_PUMP_ENABLE,
    COMMAND_CONTROL_BYTE, MEMORY_ADDR_MODE_COMMAND, MEMORY_ADDR_MODE_HORIZONTAL,
    COMMAND_CONTROL_BYTE, SEGMENT_REMAP_COMMAND,
    COMMAND_CONTROL_BYTE, COM_OUTPUT_SCAN_DIR_COMMAND,
    COMMAND_CONTROL_BYTE, COM_PINS_CONFIG_COMMAND, COM_PINS_CONFIG_128X64,
    COMMAND_CONTROL_BYTE, SET_CONTRAST_COMMAND, DEFAULT_CONTRAST,
    COMMAND_CONTROL_BYTE, SET_PRECHARGE_PERIOD_COMMAND, DEFAULT_PRECHARGE_PERIOD,
    COMMAND_CONTROL_BYTE, SET_VCOMH_DESELECT_LEVEL_COMMAND, DEFAULT_VCOMH_LEVEL,
    COMMAND_CONTROL_BYTE, ENTIRE_DISPLAY_ON_RESUME_COMMAND,
    COMMAND_CONTROL_BYTE, NORMAL_DISPLAY_COMMAND,
    COMMAND_CONTROL_BYTE, DISPLAY_ON_COMMAND,
};

#endif //COMMANDS_H
